apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin

  template:
    metadata:
      labels:
        app: admin

    spec:
      containers:
      - name: admin
        image: 547268988661.dkr.ecr.ap-south-1.amazonaws.com/tomato-admin:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 80