apiVersion: v1
kind: Secret
metadata:
  name: tomato-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://admin:admin1234@cluster0.qlvu08d.mongodb.net/tomato"
  JWT_SECRET: "random#secret"
  STRIPE_SECRET_KEY: "YOUR_STRIPE_SECRET_KEY"